-- schema.sql
-- This schema is for storing user-submitted incident reports for the SerenityEWS app.

-- Drop the table if it already exists to start fresh (useful for development).
DROP TABLE IF EXISTS reports;

-- Create a table for user-submitted reports.
CREATE TABLE reports (
    -- Using SERIAL for a simple, auto-incrementing integer ID.
    id SERIAL PRIMARY KEY,
    
    -- The URL to the uploaded photo. In a real app, you would upload the image to a service
    -- like Google Cloud Storage and store the URL here.
    photo_url TEXT NOT NULL,

    -- The user's detailed description of the incident.
    description TEXT NOT NULL,
    
    -- GPS coordinates of the incident. DECIMAL offers good precision.
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    
    -- The category determined by the AI (e.g., "Banjir", "Pohon Tumbang").
    category VARCHAR(100) NOT NULL,
    
    -- A one-sentence summary generated by the AI.
    summary TEXT,
    
    -- English keywords for the photo, generated by the AI for search purposes.
    photo_hint VARCHAR(255),
    
    -- A display name for the user who submitted the report.
    -- In a full application, this would likely be a foreign key to a 'users' table.
    user_display_name VARCHAR(100) NOT NULL,
    
    -- The timestamp when the report was created.
    -- TIMESTAMPTZ is recommended to store timezone information, which is crucial for incident reporting.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add an index on the creation timestamp for faster sorting of recent reports.
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);

-- Add a basic index on location for faster geospatial queries if needed.
CREATE INDEX idx_reports_lat_lon ON reports(latitude, longitude);

-- Add comments to columns for better documentation.
COMMENT ON COLUMN reports.id IS 'Unique identifier for each report.';
COMMENT ON COLUMN reports.photo_url IS 'URL of the photo of the incident.';
COMMENT ON COLUMN reports.description IS 'User-provided description of the incident.';
COMMENT ON COLUMN reports.latitude IS 'Latitude of the incident location.';
COMMENT ON COLUMN reports.longitude IS 'Longitude of the incident location.';
COMMENT ON COLUMN reports.category IS 'AI-generated category for the incident.';
COMMENT ON COLUMN reports.summary IS 'AI-generated summary of the incident.';
COMMENT ON COLUMN reports.photo_hint IS 'AI-generated keywords for the photo for searchability.';
COMMENT ON COLUMN reports.user_display_name IS 'Display name of the user who submitted the report.';
COMMENT ON COLUMN reports.created_at IS 'Timestamp when the report was created.';